# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-02 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20171103_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
