# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-02 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20171103_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rid',
            field=models.IntegerField(default=0),
        ),
    ]
