# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='sign',
        ),
    ]
