# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_remove_site_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
